name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Cython
        run: |
          pip install cython

      - name: Build Cython extensions
        run: |
          python setup.py build_ext --inplace

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)/vcfparser" >> $GITHUB_ENV

      - name: Test with pytest
        run: |
          pip install pytest
          # py.test
          python -m pytest tests/
